services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
